var annotated_dup =
[
    [ "Ciel", "class_ciel.html", "class_ciel" ],
    [ "Coords", "class_coords.html", "class_coords" ],
    [ "Disk", "class_disk.html", "class_disk" ],
    [ "Ellipse", "class_ellipse.html", "class_ellipse" ],
    [ "Ellipse_gradient", "class_ellipse__gradient.html", "class_ellipse__gradient" ],
    [ "Etoile", "class_etoile.html", "class_etoile" ],
    [ "Etoilefilante", "class_etoilefilante.html", "class_etoilefilante" ],
    [ "FILE_buffer", "class_f_i_l_e__buffer.html", "class_f_i_l_e__buffer" ],
    [ "FILE_buffer_style", "struct_f_i_l_e__buffer__style.html", "struct_f_i_l_e__buffer__style" ],
    [ "Fond", "class_fond.html", "class_fond" ],
    [ "Gradient", "class_gradient.html", "class_gradient" ],
    [ "Herbe", "class_herbe.html", "class_herbe" ],
    [ "Jour", "class_jour.html", "class_jour" ],
    [ "Line", "class_line.html", "class_line" ],
    [ "Lune", "class_lune.html", "class_lune" ],
    [ "Montagne", "class_montagne.html", "class_montagne" ],
    [ "Nuage", "class_nuage.html", "class_nuage" ],
    [ "Nuit", "class_nuit.html", "class_nuit" ],
    [ "Objet", "class_objet.html", "class_objet" ],
    [ "OptionGrad", "class_option_grad.html", "class_option_grad" ],
    [ "Plaine", "class_plaine.html", "class_plaine" ],
    [ "Plan", "class_plan.html", "class_plan" ],
    [ "Plan_eau", "class_plan__eau.html", "class_plan__eau" ],
    [ "Polygone", "class_polygone.html", "class_polygone" ],
    [ "Polygone_gradient", "class_polygone__gradient.html", "class_polygone__gradient" ],
    [ "Polyline", "class_polyline.html", "class_polyline" ],
    [ "Primitive", "class_primitive.html", "class_primitive" ],
    [ "Relief", "class_relief.html", "class_relief" ],
    [ "Scene", "class_scene.html", "class_scene" ],
    [ "Soir", "class_soir.html", "class_soir" ],
    [ "Soleil", "class_soleil.html", "class_soleil" ],
    [ "Svgfile", "class_svgfile.html", "class_svgfile" ],
    [ "Triangle", "class_triangle.html", "class_triangle" ],
    [ "Vague", "class_vague.html", "class_vague" ]
];